global:
  scrape_interval: 10s
  scrape_timeout: 10s

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
          - 'aligned-worker:8000'
          - 'aligned-server:8000'
          - 'aligned-ground-truth:8000'
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']